<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vdc01dlap0337" name="net.valtech.testNG.TesNGDependsOnGroupsExample" tests="10" failures="0" timestamp="9 Aug 2017 13:21:08 GMT" time="0.029" errors="2">
  <testcase name="testDelete" time="0.001" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
  <testcase name="testUpdate" time="0.001" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
  <testcase name="openConfirmationDialog" time="0.002" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
  <testcase name="backendGroupDependentTest1" time="0.000" classname="net.valtech.testNG.TesNGDependsOnGroupsExample">
    <error type="java.lang.Throwable" message="Method TesNGDependsOnGroupsExample.backendGroupDependentTest1()[pri:0, instance:net.valtech.testNG.TesNGDependsOnGroupsExample@ae45eb6] depends on not successfully finished methods in group &quot;security&quot;">
      <![CDATA[java.lang.Throwable: Method TesNGDependsOnGroupsExample.backendGroupDependentTest1()[pri:0, instance:net.valtech.testNG.TesNGDependsOnGroupsExample@ae45eb6] depends on not successfully finished methods in group "security"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- backendGroupDependentTest1 -->
  <testcase name="accessAdminPage" time="0.008" classname="net.valtech.testNG.TesNGDependsOnGroupsExample">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at net.valtech.testNG.TesNGDependsOnGroupsExample.accessAdminPage(TesNGDependsOnGroupsExample.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- accessAdminPage -->
  <testcase name="openFileDialog" time="0.002" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
  <testcase name="backendGroupDependentTest2" time="0.006" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
  <testcase name="uiGroupDependentTest" time="0.002" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
  <testcase name="accessHomePage" time="0.003" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
  <testcase name="testInsert" time="0.004" classname="net.valtech.testNG.TesNGDependsOnGroupsExample"/>
</testsuite> <!-- net.valtech.testNG.TesNGDependsOnGroupsExample -->
